### ISSUE TITLE
Help installing

### ISSUE THREAD

**Issue by canovel** [ckbaudio/WavPatcher#2]
I found your page from a thread on the pioneer forums. Bandcamp wavs not running on cdj's i've found your code but im Struggling to start the setup. I've installed pillow and pip. Do i run the code from python or cmd? 

not sure what i have to do next, not sure if i can leave an e-mail on here or not. Any help is appreciated

**Comment by camm9909** [comment]
Hi mate,

Assuming you've installed Python3 on your system, it should just be a case of click-and-run via the binaries found in the [release section](https://github.com/ckbaudio/WavPatcher/releases/tag/092b) for your operating system.

Best regards,
Cam

**Comment by canovel** [comment]
Sorted, That was far too easy.

Thanks for your help!
